image: python:3.8

pipelines:
  default:
    - step: &test
        name: Mock tests
        script:
          - echo "TODO add tests"

  branches:
    master:
      - step: *test
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          script:
            - echo "Deploy new code"
            - ssh -i /opt/atlassian/pipelines/agent/ssh/id_rsa -o 'StrictHostKeyChecking=no' root@membot.ru "cd /home/www/td && git fetch && git checkout -f origin/master" # путь до ssh-ключа отличается от дефолтного
            - echo "Restart Bot"
            - ssh -i /opt/atlassian/pipelines/agent/ssh/id_rsa -o 'StrictHostKeyChecking=no' root@membot.ru "cd /home/www/td"

    pull-requests:
      # Цель запустится при наличии открытого PR на любой ветке
      '**':
        - step: *test
